const productModel = require('../models/productModel');

const path = require('path');
const fs = require('fs');

const UPLOAD_DIR = path.join(__dirname, '../public/uploads');
const DEFAULT_IMAGE = 'noTexture.png';

// Matches filenames generated by middleware/upload.js (32 hex chars + extension).
// Only files matching this pattern are safe to delete — anything else could be
// a seeded/stock image potentially shared by other products.
const GENERATED_UPLOAD_PATTERN = /^[0-9a-f]{32}\.(png|jpg|webp|gif)$/i;

// Best-effort delete of a previously-uploaded image, so replacing an image
// doesn't leave the old file orphaned on disk. Never touches the default image
// or pre-seeded stock images, and quietly ignores errors since this is cleanup only.
function deleteUploadedImage(filename) {
  if (!filename || filename === DEFAULT_IMAGE) return;
  if (!GENERATED_UPLOAD_PATTERN.test(filename)) return;
  fs.unlink(path.join(UPLOAD_DIR, filename), () => {});
}

// GET /products — the internal-portal catalog page
// Supports optional search (?searchQuery=), price sort (?sortBy=price_asc|price_desc),
// and availability filter (?availability=in_stock|out_of_stock), all combinable.
function showProductsPage(req, res) {
  const { searchQuery, sortBy, availability, uploadError } = req.query;   // add uploadError here
  const products = productModel.getFilteredProducts({ searchQuery, sortBy, availability });
  res.render('products', {
    products,
    searchQuery: searchQuery || '',
    sortBy: sortBy || '',
    availability: availability || '',
    uploadError: uploadError || ''   // and add this line
  });
}

// POST /products/add — create a new product from the "Add New Product" form
function addProduct(req, res) {
  const { name, description, quantity, price } = req.body;
  if (!name || quantity === undefined || price === undefined) {
    return res.status(400).redirect('/products');
  }
  const image_url = req.file ? req.file.filename : 'noTexture.png';
  productModel.createProduct({
    name,
    description: description || '',
    image_url,
    quantity: Number(quantity),
    price: Number(price)
  });
  res.redirect('/products');
}

// GET /products/modify/:id — show the edit form for a single product
function showEditProductPage(req, res) {
  const { id } = req.params;
  const { uploadError } = req.query;

  const product = productModel.getProductById(id);
  if (!product) {
    return res.status(404).redirect('/products');
  }

  res.render('editProduct', {
    product,
    uploadError: uploadError || ''
  });
}

// POST /products/modify/:id — apply edits, optionally replacing the image
function updateProduct(req, res) {
  const { id } = req.params;
  const { name, description, quantity, price } = req.body;

  const existing = productModel.getProductById(id);
  if (!existing) {
    return res.status(404).redirect('/products');
  }

  if (!name || quantity === undefined || price === undefined) {
    return res.status(400).redirect(`/products/modify/${id}`);
  }

  // Keep the existing image unless a new one was uploaded
  const image_url = req.file ? req.file.filename : existing.image_url;

  productModel.updateProduct(id, {
    name,
    description: description || '',
    image_url,
    quantity: Number(quantity),
    price: Number(price)
  });

  // If a new image replaced an old uploaded one, clean up the old file
  if (req.file && existing.image_url !== image_url) {
    deleteUploadedImage(existing.image_url);
  }

  res.redirect('/products');
}

// POST /products/remove/:id — delete a product from the catalog
function removeProduct(req, res) {
  const { id } = req.params;

  const existing = productModel.getProductById(id);
  productModel.deleteProduct(id);

  if (existing) {
    deleteUploadedImage(existing.image_url);
  }

  res.redirect('/products');
}
module.exports = {
  showProductsPage,
  addProduct,
  showEditProductPage,
  updateProduct,
  removeProduct
};
